FROM node:22-alpine

WORKDIR /app
COPY frontend/package*.json ./
RUN npm install

COPY frontend ./

ENV NEXT_PUBLIC_API_URL=http://localhost:8000
EXPOSE 3000
CMD ["npm", "run", "dev", "--", "-p", "3000"]
