import dotenv from "dotenv";
import { connectDB } from "../config/db.js";
import Movie from "../models/Movie.js";

dotenv.config();

const seed = [
  {
    title: "Interstellar",
    year: 2014,
    genres: ["Sci-Fi", "Drama"],
    tags: ["space", "wormhole"],
    posterUrl: "https://image.tmdb.org/t/p/w500/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
    trailerUrl: "https://www.youtube.com/embed/zSWdZVtXT7E",
    description: "A team travels through a wormhole to save humanity.",
    cast: ["Matthew McConaughey", "Anne Hathaway"],
    featured: true,
    trendingScore: 95,
  },
  {
    title: "Inception",
    year: 2010,
    genres: ["Sci-Fi", "Thriller"],
    tags: ["dream", "mind"],
    posterUrl: "https://image.tmdb.org/t/p/w500/8IB2e4r4oVhHnANbnm7O3Tj6tF8.jpg",
    trailerUrl: "https://www.youtube.com/embed/YoHD9XEInc0",
    description: "A thief steals secrets through dream-sharing technology.",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt"],
    trendingScore: 88,
  },
  {
    title: "The Matrix",
    year: 1999,
    genres: ["Sci-Fi", "Action"],
    tags: ["simulation", "ai"],
    posterUrl: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    trailerUrl: "https://www.youtube.com/embed/vKQi3bBA1y8",
    description: "A hacker discovers reality is a simulation.",
    cast: ["Keanu Reeves", "Carrie-Anne Moss"],
    trendingScore: 90,
  },
  {
    title: "Blade Runner 2049",
    year: 2017,
    genres: ["Sci-Fi", "Mystery"],
    tags: ["ai", "future"],
    posterUrl: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    trailerUrl: "https://www.youtube.com/embed/gCcx85zbxz4",
    description: "A young blade runner uncovers a secret tied to humanity.",
    cast: ["Ryan Gosling", "Harrison Ford"],
    trendingScore: 84,
  },
  {
    title: "Arrival",
    year: 2016,
    genres: ["Sci-Fi", "Drama"],
    tags: ["linguistics", "aliens"],
    posterUrl: "https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg",
    trailerUrl: "https://www.youtube.com/embed/tFMo3UJ4B4g",
    description: "A linguist works to communicate with visitors from beyond Earth.",
    cast: ["Amy Adams", "Jeremy Renner"],
    trendingScore: 82,
  },
  {
    title: "Dune",
    year: 2021,
    genres: ["Sci-Fi", "Adventure"],
    tags: ["desert", "prophecy"],
    posterUrl: "https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    trailerUrl: "https://www.youtube.com/embed/8g18jFHCLXk",
    description: "A noble family is drawn into a war over a rare and powerful resource.",
    cast: ["Timothee Chalamet", "Zendaya"],
    trendingScore: 92,
  },
  {
    title: "Tenet",
    year: 2020,
    genres: ["Sci-Fi", "Action"],
    tags: ["time", "espionage"],
    posterUrl: "https://image.tmdb.org/t/p/w500/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
    trailerUrl: "https://www.youtube.com/embed/LdOM0x0XDMo",
    description: "A secret agent manipulates time to stop global catastrophe.",
    cast: ["John David Washington", "Robert Pattinson"],
    trendingScore: 80,
  },
  {
    title: "Ex Machina",
    year: 2014,
    genres: ["Sci-Fi", "Thriller"],
    tags: ["ai", "ethics"],
    posterUrl: "https://image.tmdb.org/t/p/w500/dmJW8IAKHKxFNiUnoDR7JfsK7Rp.jpg",
    trailerUrl: "https://www.youtube.com/embed/EoQuVnKhxaM",
    description: "A programmer evaluates the consciousness of an advanced AI.",
    cast: ["Alicia Vikander", "Domhnall Gleeson"],
    trendingScore: 78,
  },
  {
    title: "The Grand Budapest Hotel",
    year: 2014,
    genres: ["Comedy", "Drama"],
    tags: ["hotel", "adventure", "heist"],
    posterUrl: "https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg",
    trailerUrl: "https://www.youtube.com/embed/1Fg5iWmQjwk",
    description: "A whimsical concierge and his protege navigate mystery and chaos in a grand hotel.",
    cast: ["Ralph Fiennes", "Tony Revolori"],
    trendingScore: 81,
  },
  {
    title: "Toy Story 3",
    year: 2010,
    genres: ["Animation", "Family"],
    tags: ["toys", "friendship", "adventure"],
    posterUrl: "https://image.tmdb.org/t/p/w500/AbbXSPMOwdvwWZgVN0nabZq03Ec.jpg",
    trailerUrl: "https://www.youtube.com/embed/JcpWXaA2qeg",
    description: "Woody and friends face an uncertain future as Andy prepares for college.",
    cast: ["Tom Hanks", "Tim Allen"],
    trendingScore: 85,
  },
  {
    title: "The Conjuring",
    year: 2013,
    genres: ["Horror", "Mystery"],
    tags: ["haunted", "paranormal", "investigation"],
    posterUrl: "https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg",
    trailerUrl: "https://www.youtube.com/embed/k10ETZ41q5o",
    description: "Paranormal investigators help a family terrorized by a dark presence.",
    cast: ["Vera Farmiga", "Patrick Wilson"],
    trendingScore: 79,
  },
  {
    title: "La La Land",
    year: 2016,
    genres: ["Romance", "Music"],
    tags: ["jazz", "dreams", "love"],
    posterUrl: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    trailerUrl: "https://www.youtube.com/embed/0pdqf4P9MB8",
    description: "An aspiring actress and a jazz musician fall in love while chasing their dreams.",
    cast: ["Emma Stone", "Ryan Gosling"],
    trendingScore: 83,
  },
  {
    title: "Saving Private Ryan",
    year: 1998,
    genres: ["War", "History"],
    tags: ["ww2", "army", "mission"],
    posterUrl: "https://image.tmdb.org/t/p/w500/uqx37cS8cpHg8U35f9U5IBlrCV3.jpg",
    trailerUrl: "https://www.youtube.com/embed/9CiW_DgxCnQ",
    description: "A squad sets out on a dangerous mission to find and bring home a paratrooper.",
    cast: ["Tom Hanks", "Matt Damon"],
    trendingScore: 84,
  },
  {
    title: "The Pursuit of Happyness",
    year: 2006,
    genres: ["Drama", "Family"],
    tags: ["inspiration", "father", "survival"],
    posterUrl: "https://image.tmdb.org/t/p/w500/lBYOKAMcxIvuk9s9hMuecB9dPBV.jpg",
    trailerUrl: "https://www.youtube.com/embed/89Kq8SDyvfg",
    description: "A struggling salesman fights for a better future for himself and his son.",
    cast: ["Will Smith", "Jaden Smith"],
    trendingScore: 82,
  },
  {
    title: "The Social Network",
    year: 2010,
    genres: ["Drama", "History"],
    tags: ["startup", "facebook", "technology"],
    posterUrl: "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
    trailerUrl: "https://www.youtube.com/embed/lB95KLmpLR4",
    description: "The rise of Facebook and the conflicts that followed its explosive growth.",
    cast: ["Jesse Eisenberg", "Andrew Garfield"],
    trendingScore: 80,
  },
  {
    title: "Shrek",
    year: 2001,
    genres: ["Animation", "Comedy"],
    tags: ["fairytale", "ogre", "friendship"],
    posterUrl: "https://image.tmdb.org/t/p/w500/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg",
    trailerUrl: "https://www.youtube.com/embed/CwXOrWvPBPk",
    description: "An ogre sets out on an unexpected quest and discovers friendship and love.",
    cast: ["Mike Myers", "Eddie Murphy"],
    trendingScore: 86,
  },
  {
    title: "Mad Max: Fury Road",
    year: 2015,
    genres: ["Action", "Adventure"],
    tags: ["apocalypse", "chase", "rebellion"],
    posterUrl: "https://image.tmdb.org/t/p/w500/hA2ple9q4qnwxp3hKVNhroipsir.jpg",
    trailerUrl: "https://www.youtube.com/embed/hEJnMQG9ev8",
    description: "A road warrior joins rebels in a high-octane escape through a wasteland.",
    cast: ["Tom Hardy", "Charlize Theron"],
    trendingScore: 89,
  },
  {
    title: "Coco",
    year: 2017,
    genres: ["Animation", "Music"],
    tags: ["family", "tradition", "journey"],
    posterUrl: "https://image.tmdb.org/t/p/w500/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg",
    trailerUrl: "https://www.youtube.com/embed/Rvr68u6k5sI",
    description: "A young musician enters the Land of the Dead to uncover his family story.",
    cast: ["Anthony Gonzalez", "Gael Garcia Bernal"],
    trendingScore: 87,
  },
];

async function run() {
  await connectDB(process.env.MONGO_URI);
  await Movie.deleteMany({});
  await Movie.insertMany(seed);
  console.log("Seeded movies:", seed.length);
  process.exit(0);
}

run();
